---
# tasks file for duplicity
- name:   update alternatives for python
  alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python3

- name:   install duplicity on ubuntu 18.04
  include_tasks: install-ubuntu-18.04.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "18.04"

- name: install packages
  package:
    name:
      - awscli
      - duplicity
      - python3-boto
      - python3-boto3
      - python3-botocore
      - python3-pip
    state: latest

- name: install s3cmd
  pip:
    name:
      - s3cmd
      - boto
    executable: pip3

- name: install duplicity-backup.sh script
  get_url:
    url:  https://raw.githubusercontent.com/zertrin/duplicity-backup.sh/dev/duplicity-backup.sh
    dest: /usr/local/bin/duplicity-backup.sh
    mode: 0755
