---
# handlers file for elasticsearch
- name:    restart elasticsearch
  service: name=elasticsearch state=restarted enabled=yes

- name:    restart nginx
  service: name=nginx state=restarted enabled=yes
